FROM centos:7.9.2009
ARG BUILD_URL
ARG RPM
COPY ./python_requirements.txt ./tmp/python_requirements.txt
RUN yum install --nogpgcheck -y python3 yum-utilis sudo which python3-pip
RUN pip3 install --no-cache-dir --trusted-host $(echo $BUILD_URL \
  | awk -F '/' '{print $3}')  -i $BUILD_URL/python_deps \
  -r ./tmp/python_requirements.txt
COPY ./tmp/*.rpm /tmp/
RUN rpm -ivh ./tmp/$RPM
RUN rm -rf /var/cache/yum
LABEL name="cortx-status" vendor="Seagate"
CMD ["/bin/bash"]
